### ISSUE TITLE
Feature Request: search application

### ISSUE THREAD

**Issue by mystery4f** [sigoden/window-switcher#105]
Like PowerToys Run, it can search.

![PixPin_2024-04-20_19-08-08](https://github.com/sigoden/window-switcher/assets/40482524/ee843139-98fd-4ea4-9141-00cba1926ead)

**Comment by sigoden** [comment]
window-switcher only supports two shortcut keys to switch windows/apps and does not support anything else.
Sorry, this feature will not be supported.
