### ISSUE TITLE
Feature Request: Option to stay window gallary status and  can config keybindings with select window, quit alt+tab etc..

### ISSUE THREAD

**Issue by soluty** [sigoden/window-switcher#106]
Windows has native alt+tab implementation which is this software do,  but it can not stay  in the gallary, so if i  press more alt-tab, i have no chance to fix my fault but cycle all windows again,  in  macos   there is an app called  alttab , it can stay with gallary view, and you can press left right to navigate, if you select window, press enter or space to select, if you dont want to doit, just press esc to escape,  this feature  is awesome, how do you think about it?

**Comment by sigoden** [comment]
We will not support this features.

The core value of window-switcher is simplicity and speed. There are only two shortcut keys, paired with shift to reverse.
It is recommended that you use shift to reverse, or you can use the mouse to pick the target application.
