### ISSUE TITLE
log not work

### ISSUE THREAD

**Issue by Tback1** [sigoden/window-switcher#108]
```ini
[log]

# Log level can be one of off,error,warn,info,debug,trace.
level = debug

# Log file path. 
path = W:\2\switch.log
```
I put a blank log file in the `W:\2\switch.log` but no content output to it.
but output to `w:\2switch.log`

**Comment by sigoden** [comment]
The file path is invalid. Didn't window-switcher.exe notify you? @Tback1 

The path needs escaping.
```
path = W:\\2\\switch.log
 ```

**Comment by Tback1** [comment]
no mention to me. I guess need double \\ so maybe it's a bug

**Comment by sigoden** [comment]
I can confirm that an msgbox will pop up if the log path is incorrect.
![image](https://github.com/sigoden/window-switcher/assets/4012553/d5f2555a-e823-4b85-b7d5-8b761bc31496)
