### ISSUE TITLE
Failed to add trayicon, Unspecified error (0x80004005)

### ISSUE THREAD

**Issue by aravindhp** [sigoden/window-switcher#111]
I have windows-switcher running as Administrator on startup. Every time Windows reboots, I get the following error window:

![image](https://github.com/sigoden/window-switcher/assets/11638995/fdde47d7-42f4-4fad-aba7-08d88560c9ee)

I then have to manually start windows-switcher to run as Administrator. Not sure if this is a bug or am I misconfiguring the app.

Here is the full ini file:
```
# Whether to show trayicon, yes/no
trayicon = yes 

[switch-windows]

# Hotkey to switch windows
hotkey = alt+`

# List of hotkey conflict apps
# e.g. game1.exe,game2.exe
blacklist =

# Ignore minimal windows
ignore_minimal = no

[switch-apps]

# Whether to enable switching apps
enable = no

# Hotkey to switch apps
hotkey = alt+tab

# Ignore minimal windows
ignore_minimal = no

[log]

# Log level can be one of off,error,warn,info,debug,trace.
level = info 

# Log file path. 
path = 
```

**Comment by sigoden** [comment]
How do you add WindowSwitcher service?

Please run ` Get-ScheduledTask -TaskName WindowSwitcher | Export-ScheduledTask` to export the WindowSwitcher service,
then post it here so I can troubleshoot it.

@aravindhp

**Comment by sigoden** [comment]
AIChat now fully supports the function calling feature.

- [x] Supports two function types: retrieve and execute
- [x] Supports multi-calls and multi-steps
- [x] Works within a role/session
- [x] Have function filter
- [x] Executes function calls in parallel

**Comment by aravindhp** [comment]
> How did you add WindowSwitcher scheduled task?
> 
> If it was not added by window-switcher.exe, please remove old one first, then add a new one by `trayicon > startup` (ensure window-switch runs as administrator).

I added it through windows-switcher.exe using `trayicon -> startup` after launching it as administrator.


> If it was added by window-switcher.exe, please run ` Get-ScheduledTask -TaskName WindowSwitcher | Export-ScheduledTask` to export your WindowSwitcher scheduled task, then post it here so I can troubleshoot it.
```
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.3" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2024-04-23T14:57:23</Date>
    <Author>ARAVINDH-SD\Aravindh</Author>
    <URI>\WindowSwitcher</URI>
    <SecurityDescriptor></SecurityDescriptor>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <StartBoundary>2024-04-23T14:57:00</StartBoundary>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>Aravindh</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <DisallowStartOnRemoteAppSession>false</DisallowStartOnRemoteAppSession>
    <UseUnifiedSchedulingEngine>false</UseUnifiedSchedulingEngine>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions>
    <Exec>
      <Command>C:\Users\Aravindh\AppData\Local\Programs\window-switcher\window-switcher.exe</Command>
    </Exec>
  </Actions>
</Task>
```

**Comment by aravindhp** [comment]
> Due to a lack of feedback, this issue is being closed.

Apologies for the delay in responding. I am an open source maintainer in the SIG-windows area of Kubernetes and I feel the pain of issues that don't have enough detail. However I suggest giving the easier more time to provide the feedback may be at least a week.

**Comment by sigoden** [comment]
Another place where Windows sucks. With the same configuration, some computers work but others don't.

Sorry. I don't know how to deal with this problem. I can only give you suggestions.

### Try 1

Adjust the `configuration for` to match your windows version

![image](https://github.com/sigoden/window-switcher/assets/4012553/cb902161-8512-4a6c-b666-ce0aa7eee4d6)

### Try 2

Delay task

![image](https://github.com/sigoden/window-switcher/assets/4012553/d14e3436-6e13-47c5-a5ad-1e526b083859)

Please let me know the result.

**Comment by joelcho** [comment]
I encountered this issue as well, but the error isn't 100% reproducible.
There is a chance that this error appears after booting up, but I haven't figured out a consistent way to trigger it.

Last night, my computer unexpectedly lost power, and when I booted it up at noon, the issue reappeared.

OS: Windows 11 23H2 22631.3593.

I've followed the instructions above to configure the task (delay of 15 seconds, hide Configure for...).

If this error occurs again I will provide more details.

**Comment by joelcho** [comment]
I find out how to trigger this error with high probability, which is to do logout then login (when I turn off the 30 second delay).

Maybe OS was too busy when starting up (or user login) or there were some `Order` issues that caused the `tray window` to not be initialized when Switcher started.

see [ANc8Ycyl3MJ](https://groups.google.com/g/microsoft.public.platformsdk.shell/c/7PgRUgGpTTc/m/_ANc8Ycyl3MJ) (Click Show trimmed content)

I think the following solution is good

1. Add a 30 second delay when creating a task
2. When calling Shell_NotifyIconW(NIM_ADD, x) fails, call the sleep(N) and try again

**Comment by sigoden** [comment]
@joelcho 
Solution 2 looks good, could your submit a PR?
