### ISSUE TITLE
Multilanguage GUI

### ISSUE THREAD

**Issue by bovirus** [sigoden/window-switcher#113]
@sigoden 

Thanks for the program.

Could you please consider to modify the source code to enable multilanguage GUI?

Thanks.

**Comment by sigoden** [comment]
No. The only text in this application is as follows:

![image](https://github.com/sigoden/window-switcher/assets/4012553/f020be4c-4505-4311-8a79-bc694fa0a8cd)

Is it necessary to have multiple languages?

**Comment by bovirus** [comment]
@sigoden 

These are three strings that could be translated.

Please take care that no info about programm running in the tray option. Ex:

Configure Window switcher -> Impostazioni Windows Switcher
Automatic Startup -> Avvio automatico
Exit from Windows Switcher -> Esci da Windows Switcher

Or make on top the program name caption (Windows Switcher) and can use simple command
Configure -> Impostazioni
Exit -> Esci

Thanks.

**Comment by sigoden** [comment]
Still, I'm not prepared to support muti-lang.

I don't believe language will be a barrier for users of this software.

**Comment by bovirus** [comment]
@sigoden 

Sorry but I'm not agree.
I didn't udnerstand why not implemnt it.
Thanks.
