### ISSUE TITLE
A possible option to have ESC exit the switcher?

### ISSUE THREAD

**Issue by mcuiux** [sigoden/window-switcher#115]
I'd like to add a +1 for this feature request, it's damn near perfect.

Canceling out of an action without performing it is an important part of any UX, I'd really appreciate this as an option in the config.

There's an autohotkey version of this (https://github.com/Osmagtor/AppSwitcher/ - I modified it and posted my changes in the "issues" - but I'm not the best at it. I'd prefer to use this Rust version, if it could exit when I press Esc - as that's what I use when I work on my Mac at home :)

Thanks for making this regardless!

**Comment by sigoden** [comment]
The switch-app GUI, activated by pressing `Alt+Tab`, remains visible only while the `Alt` key is held down and disappears upon its release.

There is no need for additional ESC exit.

In addition, This tool's most notable feature is its speed and simplicity. It has only two hotkeys（as promised in the readme):
-  `Alt+Tab` to switch between apps 
- ``` Alt+` ``` to switch between windows of the same app

No additional shortcut keys or functions are planned for the foreseeable future.

**Comment by mcuiux** [comment]
Thank you still, it's an awesome app.
The switcher switches to the highlighted app when I release "alt", and then exits.
The proposed "esc" press would only exit the switcher, and not make the switch to the app.

I do appreciate your firmness on keeping this App minimal, could you perhaps give me a pointer what line(s) I'd need to go to / alter to fork it and put this in myself? Much obliged.

**Comment by mcuiux** [comment]
Hey! I see I missed some notifications, I just wanted to say: *thank you* for this 🙏
