### ISSUE TITLE
In Alt+Tab mode the foreground and background colors are too similar

### ISSUE THREAD

**Issue by hoang-dt** [sigoden/window-switcher#119]
Thank you for this useful program! I have a small request: the background (highlight) color and the foreground color in Alt + Tab mode are both some dark gray colors, making it very hard to discern which window is being highlighted to switch to. It would be nice to have the colors more distinct.

**Comment by sigoden** [comment]
![image](https://github.com/sigoden/window-switcher/assets/4012553/d3bd231e-a57b-44d3-8128-c3c3097654a4)

We believe the current foreground/background contrast is sufficient and doesn't require modification.
