### ISSUE TITLE
Not starting up with Windows 11

### ISSUE THREAD

**Issue by JensErikChristiansen** [sigoden/window-switcher#121]
I have the app set to startup with admin privileges, but it doesn't start up with Windows.
![image](https://github.com/user-attachments/assets/2b7d3926-7306-4dcd-a492-81fbf6b9af34)

![image](https://github.com/user-attachments/assets/e9d99f18-5032-421f-be7b-ca17880b9716)
I see an option to "Register this program for restart", but thought I check here first before trying to enable it.

I have tried placing the folder in Program Files and on the Desktop.

**Comment by sigoden** [comment]
We have tested it on Win11 and found no problem.

Window-switcher relies on scheduled tasks for automatic startup with administrator privileges. 

![image](https://github.com/user-attachments/assets/3ced8078-12f1-4714-815f-6d5221f547ac)

Check the `Task Scheduler` app for a task named `WindowSwitcher`. 

If it exists, but `window-switcher.exe` still won't start, **you should ask Windows for help.**
