### ISSUE TITLE
windows-switcher.exe

### ISSUE THREAD

**Issue by mrosen88** [sigoden/window-switcher#123]
I need help finding Windows-switcher.exe on Windows 11 after following instructions.  It does not appear to be there. Thanks.

**Comment by sigoden** [comment]
Windows Switcher does not need to be installed. Simply download and unzip the zip file, then click `window-switcher.exe` to run it.

**Comment by mrosen88** [comment]
Thanks but I could not find the .exe file ?

________________________________

**Comment by sigoden** [comment]
Did you really read the readme?

download the zip file from github releases, unzip it, and there is the window-switch.exe file in it.

**Comment by mrosen88** [comment]
I did read it. I find windows-switcher  configuration settings only- no exe file.

________________________________

**Comment by sigoden** [comment]
Maybe your window explorer hides the exe suffix.
There is only one file in the zip, what else is it besides exe?

**Comment by mrosen88** [comment]
Hi, Here is a screenshot of the folder (including hidden files).

Thanks.

[https://res.cdn.office.net/assets/mail/file-icon/png/photo_16x16.png]Screenshot 2024-07-15 092434.png<https://livemanchesterac-my.sharepoint.com/:i:/g/personal/mark_rosenberg_manchester_ac_uk/EZw480NlohtBgWSwgTq3UJYBhi4bi2mHaWm8kaqKZlEoHQ>
________________________________
