### ISSUE TITLE
Windows Defender detecting windows-switcher as Trojan:Win32/Sonbokli.A!cl

### ISSUE THREAD

**Issue by aravindhp** [sigoden/window-switcher#126]
Windows Defender is detecting `windows-switcher` as `Trojan:Win32/Sonbokli.A!cl`

![image](https://github.com/user-attachments/assets/c8f213f1-22c8-436f-91ca-318719f7329c)

![image](https://github.com/user-attachments/assets/56595066-a594-41df-a439-44565104fa30)

I think you will have to submit  the latest version for malware analysis like you did before. https://github.com/sigoden/window-switcher/issues/45#issuecomment-1487646239

**Comment by sigoden** [comment]
My computer hasn't detected any viruses, and the remote system hasn't detected any viruses either.

![image](https://github.com/user-attachments/assets/afe81166-6eb6-4cce-8c9a-cf9343fa064f)

**Comment by mattytrentini** [comment]
Windows Defender is raising the same warning for me...
