### ISSUE TITLE
While alt+tab app swiching, add alt+q to quit apps 

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#127]
It would be amazing if we could add a function when, while the Alt+tab App switcher is in progress, you can just hit "q" while on an app, and it would close it.

**Comment by sigoden** [comment]
We will not support this feature. The window-switcher only focuses on switching windows.

**Comment by dmarcelino** [comment]
Hi @sigoden, thanks for Window Switcher, I've been missing "Alt+`" since moving from Linux a few years ago.

Would you reconsider @UrbanBreznik request? Closing apps from the window switcher is the other feature I miss badly on Windows.
