### ISSUE TITLE
Add rounded corners to match Windows 11 design

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#128]
If possible, add rounded corners to match Windows 11 design
<img width="965" alt="App switcher rounded corners" src="https://github.com/user-attachments/assets/0ed33893-ab79-4a12-9360-f58d28d5b730">

**Comment by sigoden** [comment]
As for the style, different people have different opinions.

We plan to keep the issue open, and if it gets a lot of likes, we will support it.

**Comment by UrbanBreznik** [comment]
Add it as an option?

**Comment by nanoraptor** [comment]
I bump this!!!
It should not be an "**option**" , it should be the "**default**". The window switcher is supposed to work with the system and it should match the default system's aesthetics. In this case it must match the aesthetics of windows 11.

**Comment by swishlabby** [comment]
I believe this should not remain optional. Particularly since the window switcher program is intended to replace or complement system actions such as alt+tab, there should be no question about its appearance. If the developers remain unconvinced, providing it as an option in the ".ini" file would be a minimum. Nonetheless, I bump this!

**Comment by sigoden** [comment]
The UI differences between Windows 10 and Windows 11 are quite significant.

Win10 does not use rounded corner.
![image](https://github.com/user-attachments/assets/72fe87e6-dde9-4a29-a10f-215734e10303)

Win11 does use rounded corner.
![image](https://github.com/user-attachments/assets/f29a7427-f92e-49d4-9558-83b61d1bef6a)

Currently, there are more Windows 10 users.
![image](https://github.com/user-attachments/assets/84919951-d895-46a4-ae73-c5ed84146d72)

**Comment by UrbanBreznik** [comment]
Hell yeah! 🙌 Awesome 😎
