### ISSUE TITLE
BUG: Not working in windows terminal. 

### ISSUE THREAD

**Issue by nanoraptor** [sigoden/window-switcher#129]
As the title says, it is not working with windows terminal. When I click alt+`, it just types ` in the terminal. Alt+Tab works correctly tho.

**Comment by sigoden** [comment]
Cannot confirm the probem.

Tips: If you run the Windows terminal in administrator mode, you should also run the window-switcher in administrator mode.
Otherwise, it may be unable to switch due to a lack of permissions.
