### ISSUE TITLE
BUG/Feature Request: Progressive web apps are still shown as a window of my browser

### ISSUE THREAD

**Issue by nanoraptor** [sigoden/window-switcher#130]
I use Microsoft Edge and have several PWAs installed on my machine. However, when I attempt to switch between them using Alt + ` or Alt + Caps Lock (my app switching shortcut), the apps do not display their individual icons. Instead, they all show the Edge logo on the app switching screen. This makes it difficult to switch between them, which is one of the main reasons I chose to use this program. I would like to request the developers to add this feature as soon as possible.

**Comment by sigoden** [comment]
PWAs are essentially web pages. The window-switcher has no way to differentiate them.

**Comment by nanoraptor** [comment]
I strive to remain respectful as I do not pay for this software and I am not a developer. However, in my view, closing an issue without due consideration is not acceptable. But it is not impossible. I raised this issue because I utilize Progressive Web Apps (PWAs) as standalone applications; otherwise, I would simply use the web browser instead for those tasks. I want them to be separated from my browser windows and it is the main reason people use PWAs. Using the default system alt+tab displays PWAs as individual apps. My sole request is for this program to align with the system's behavior.

**Comment by nanoraptor** [comment]
The reason why this issue page exists to ask the devs to bring up features and fix bugs and not to deny them.
