### ISSUE TITLE
Bug: Start menu covers the app switcher

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#131]
If you have the start menu open, the App switcher appears beneath it:
<img width="1045" alt="chrome_SNUuIBFgE8" src="https://github.com/user-attachments/assets/d236c41e-cfac-4ce3-a432-aecfef3d1d8c">

**Comment by sigoden** [comment]
There's no way to fix this. The windows don't allow any other window to appear on top of the start menu.
