### ISSUE TITLE
Visual Bug: The app switcher grabs an old icon for the Settings app

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#132]
If you have the settings opened, it grabs an old icon of the app and not the modern one it uses:
<img width="943" alt="explorer_fSmrrX2slo" src="https://github.com/user-attachments/assets/e49320e8-91ee-493d-9d01-190941707acb">

Windows itself grabs the modern icon when in normal alt+tab or in win+tab:
<img width="277" alt="ApplicationFrameHost_9SNXpE59nB" src="https://github.com/user-attachments/assets/13ab159f-47de-40b3-9418-caba2f009e38">
<img width="177" alt="chrome_EMHXub8vdI" src="https://github.com/user-attachments/assets/a10e4b62-ccc4-4ad6-9cb0-d256a1242419">

**Comment by sigoden** [comment]
Similar to #130, there is no way to fix this.

The window switcher displays the application icon, not the window icon.
The window switcher identifies the application of the windows and groups the windows by application.

Even if two windows have different icons (such as PWAs, Settings, etc.), if they belong to the same application, only one icon (the application icon) will be displayed.

**Comment by UrbanBreznik** [comment]
That's unfortunate. Thanks for the explanation!
