### ISSUE TITLE
Request: Make it 2x bigger (as an option)

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#134]
I would love to use the app switcher exactly 2x bigger, so it's easier on the eyes when using higher resolutions. Could be added as an option. 

Current:
![App_Switcher_Request_Bigger_Current](https://github.com/user-attachments/assets/668ea997-2d1e-4634-b8f4-45e7cf01ef68)

2x Bigger:
![App_Switcher_Request_Bigger_2x](https://github.com/user-attachments/assets/85abb957-71cd-412d-a66b-f067d110652f)

----
Bonus: 2x Bigger with rounded corners =)
![App_Switcher_Request_Bigger_2x_Rounded_Corners](https://github.com/user-attachments/assets/ea4af6d1-05ea-4e91-8d43-aab2ac77c583)

**Comment by sigoden** [comment]
We will not support this feature.

1. Compared to the dock and desktop icons, the current icons is not small.
2. It is not certain that all apps have large icons. At least the current icons are commonly used, so the probability of problems is extremely low.

**Comment by UrbanBreznik** [comment]
That's a shame...  😞
