### ISSUE TITLE
Feature request: open last Explorer window on ALT+` (or if no windows opened then Quick Access, default Win+E)

### ISSUE THREAD

**Issue by DmytroSokhach** [sigoden/window-switcher#135]
It would be really handy to forget about Explorer shortcuts and just stick to ALT+`
Is it even possible?
1. Open last active Explorer window on ALT+`
2. CASE WHEN no Explorer windows just open default explorer window which is opened on Win+E (Quick Access usually)

**Comment by sigoden** [comment]
We will not support this feature.

This breaks the rules of the window-switcher and will confuse users.
