### ISSUE TITLE
Light Mode possible?

### ISSUE THREAD

**Issue by jan-the-maker** [sigoden/window-switcher#136]
Love your windows switcher ... my new default. It's just really hard to make out what's actively selected. Maybe a light mode would help? I made some mockups on the same sizes. It's just different color, an extra border and some round corners (optional) and more space between the icons would make it also easier to process - I tried to stay as close as possible to the power toys run style. 

If I can help let me know!!!

![Screenshot 2024-10-15 at 19 51 10](https://github.com/user-attachments/assets/7afa9f03-8ee9-4a69-8a1f-26735c7d7108)

**Comment by UrbanBreznik** [comment]
I bump that! I love the app, but it needs some work on the UI. Windows 11 has a really strong UI feel and everything that does not follow that fell outdated - dark and light mode, rounded corners, small external line around the switcher etc.... I recommend to work on this with a designer to not go back and forth too much =) As a graphic designer, I am available for any input as well =)
