### ISSUE TITLE
Add a hoover visual cue that you can click on an app icon

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#137]
I love that you can actually click on an icon to select the app - sometimes I have 10 or more apps open and to alt-tab to the last one takes a while - so clicking on one saves a lot of time! Love it. But it would be great to add a visual cue that that would be possible! I did not even know this was possible. It can be subtle, nothing over the top, a small outline or small background change.
<img width="1128" alt="Alt tab hoover visual cue" src="https://github.com/user-attachments/assets/a8e35022-2c7b-465a-bedb-a6e32879d662">

**Comment by sigoden** [comment]
We will not support this feature.

1. The window-switcher is a keyboard-first app; the mouse is a secondary option.
2. The window switcher does not use any UI framework, which makes it difficult to implement the hover effect effectively.
