### ISSUE TITLE
Task manager bug

### ISSUE THREAD

**Issue by UrbanBreznik** [sigoden/window-switcher#142]
When you have Task manager open (win 11), it defaults back to original alt-tab. When Task manager is not in focus, but running, it does not appear in the alt-tab as an option

<img width="1922" alt="sIMwBJFLJU" src="https://github.com/user-attachments/assets/fdc54553-f7d7-4856-bf00-904e97cafbc3">
<img width="911" alt="Photoshop_PYT3VVjXv8" src="https://github.com/user-attachments/assets/a3cda33f-add7-4f19-b3ce-c9200f87a576">

**Comment by sigoden** [comment]
You need to Running as Administrator. See https://github.com/sigoden/window-switcher?tab=readme-ov-file#running-as-administrator-optional

**Comment by UrbanBreznik** [comment]
Aaaa, yes works! Great! 👌
