### ISSUE TITLE
Add this app to chocolatey package manager

### ISSUE THREAD

**Issue by matthewh86** [sigoden/window-switcher#147]
Hello!

I think this would be great to include on the chocolatey package manager site.

https://community.chocolatey.org/packages

**Comment by sigoden** [comment]
window-switcher is a portable application that requires no installation or dependencies. 

But we also welcome installation via package managers.

**Comment by matthewh86** [comment]
I assume it will need a Github workflow to push to chocolatey whenever you make a release. Or would you just want people submitting them manually?

**Comment by matthewh86** [comment]
Hi @sigoden, how would you want this done? I could try and look into making a Github actions pipeline and make a fork+PR to push it into chocolatey, but I probably wouldn't have much time to do this in the short/medium term.

**Comment by sigoden** [comment]
We dont't want to add chocolatey in this repo.
