### ISSUE TITLE
[FR]: Switch between snap groups only

### ISSUE THREAD

**Issue by ConEstArthur** [sigoden/window-switcher#152]
I'm using windows 11 and its snap feature.
When I use alt tab to switch between the apps, it goes through all my snap groups and windows inside it.

However what I hope to achieve is when snap groups are made I only want to switch between them and not go through all the opened windows inside them.

I've searched for a solution online if I can hide individual windows from app switching when they are grouped together but I've not found a solution so far.

So I thought maybe this app could help me.

I do understand if it's not pertinent to what this software is made for.

I've found a similar thread on reddit. This is what I hope to achieve and basically just a hotkey shortcut that would let me switch between groups only -

https://www.reddit.com/r/windows/comments/157kn8q/how_to_hide_sub_windows_of_a_group_when_alttab/

Thank you ☺️

**Comment by sigoden** [comment]
Sorry, we will not support this feature.
