### ISSUE TITLE
Doesn't work when 2 input layouts selected.

### ISSUE THREAD

**Issue by Ernedhir** [sigoden/window-switcher#153]
Hello, I usually switch between two layouts throught the day frequently. In en-us there is no problem but with tr-tr **`** becomes **"** so i cannot use same shortcut. Maybe you guys could add a feature like autohotkey does? in ahk if the same issue occurs instead of mapping a character, you can use vkey and sc values.

**Comment by sigoden** [comment]
We have updated the README on this topic; please take a look.

![image](https://github.com/user-attachments/assets/b4d69a6d-d81a-47d2-9e18-ca2fc3ca178f)
