### ISSUE TITLE
Feature request: Show window list when rotating through Alt + Backtick

### ISSUE THREAD

**Issue by shinebayar-g** [sigoden/window-switcher#154]
When pressing Alt+Tab, list of available applications show up in a little window. So I can know how many different applications I'm able to rotate.

It would be nice if I'm able to show the same window list when pressing Alt+Backtick so I can know how many windows of the same application are there.
For the actual behavior, I think the current instant switch is better. When showing windows, no need to wait for user to release the keys like alt tab.

**Comment by sigoden** [comment]
We will not support this feature.

Currently, Alt+Tab is non-intrusive, switches quickly, and a complete cycle doesn't take much time; switching also previews.
We don't think displaying a window list is a good idea.

**Comment by shinebayar-g** [comment]
Okay. The reason why I suggested this is, I `Alt +Backtick` switches between the last 2 active windows, not round around. So I often forget about my 3rd or 4th window ... :D I actually like the current behavior. It's perfect, but a little indicator that there's another window hanging around in the background would've been useful. That's all.

**Comment by sigoden** [comment]
![image](https://github.com/user-attachments/assets/f6398665-5d55-497e-afb3-522d7b9d89bd)

You can hold down the `alt` key and repeatedly click the ``` ` ``` key to quickly cycle through windows of the same application. It's simple and straightforward. displaying a small widget to list windows can be distracting, we will not support it.

**Comment by elonderin** [comment]
too bad. i was wondering if i could use this project to replace my good old vistaswitcher and rather liked the preview. 
my use case is: ~10 open browser windows at any given time
