### ISSUE TITLE
Publish on winget

### ISSUE THREAD

**Issue by jahanson** [sigoden/window-switcher#155]
Hey @sigoden is it a possibility to publish this application on winget? The documentation for this is at [github.com/microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs/blob/master/doc/README.md#authoring-a-manifest)

Thank you!!

**Comment by sigoden** [comment]
I can only express my welcome and willingness to help.  But I won't push this issue because I'm not familiar with winget and I don't use it.
