### ISSUE TITLE
Windows Command Line (Administrator mode) not available in Alt Tab list

### ISSUE THREAD

**Issue by shinebayar-g** [sigoden/window-switcher#156]
I can't Alt Tab into Windows Command Line application.

To reproduce:

Open `Command Prompt` application using Administrator access.. It seems regular cmd.exe now opens Windows Terminal instead of old Command Line application.

**Comment by sigoden** [comment]
You need to run window-switcher.exe in Administrator mode so it can handle applications that run in Administrator mode.

**Comment by shinebayar-g** [comment]
Ah that makes sense. Thanks.
