### ISSUE TITLE
Feature request - (Alt-`) to reverse direction of (Alt-tab) selection when switching apps is enabled

### ISSUE THREAD

**Issue by ryanfeist** [sigoden/window-switcher#157]
Similar to how macOS handles it.  When Switching apps is enabled and entered (Alt-tab) have the ability to not only traverse the list to the right (tab) but also traverse the list to the left (`).  Let me know if you need further clarification otherwise I love the app! Windows native app/window switching is a mess and this cleans it up magnificently! Thanks, Ryan

**Comment by sigoden** [comment]
We will not support this feature, but we do support reverse with the additional `shift` key.
