### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Shuraken007** [sigoden/window-switcher#46]
Hello there.
Trying this app, but nothing works.
It runned without errors, I see it at system tray, but alt+tab get default system behavior. 
alt+` not works

Windows specifications:
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎1/‎3/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

```
$ ls
        Directory: C:\tools\window-switcher


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---         5/12/2023   6:20 AM         297472 ﬓ  window-switcher_32.exe
-a---         5/12/2023   6:04 AM         342016 ﬓ  window-switcher_64.exe
-a---         5/12/2023   6:20 AM            288   window-switcher.ini

cat .\window-switcher.ini  
# Whether to show trayicon, yes/no
trayicon = yes

[switch-windows]

# Hotkey to switch windows
hotkey = alt+`

# List of hotkey conflict apps
# e.g. game1.exe,game.exe
blacklist =

[switch-apps]

# Whether to enable switching apps
enable = yes

# Hotkey to switch apps
hotkey = alt+tab
```

**Comment by sigoden** [comment]
Append follow settings to `window-switcher.ini` to enable log
```
[log]
level = debug
path = window-switcher.log
```
The restart window-swither.exe, try again, submit `window-switcher.log` to this issue. please.

**Comment by Shuraken007** [comment]
Hi there again. Tested it one more time.
alt+` - works only with visible windows. 
Case I fold with minimize one of them (alt+space+n) - your app don't see it.
![Screenshot_1](https://github.com/sigoden/window-switcher/assets/23379636/dd430d33-ffea-410a-8c58-332eba7932b1)
![Screenshot_2](https://github.com/sigoden/window-switcher/assets/23379636/24470c81-07d2-4114-a883-bebad431d624)

Here is log for switching between same app - explorer.
[window-switcher_same_app_switch.log](https://github.com/sigoden/window-switcher/files/11472101/window-switcher_same_app_switch.log)

alt+tab not works , have default windows 11 switcher
![IMG-0659](https://github.com/sigoden/window-switcher/assets/23379636/994f59e2-8801-49f2-9e41-9bd769d2bc08)

Here is fresh log for alt+tab attempt
[window-switcher_diverse_app.log](https://github.com/sigoden/window-switcher/files/11472106/window-switcher_diverse_app.log)

**Comment by Shuraken007** [comment]
If you help me to setup environment to build app, e.g. fast way to install cargo / required libs e.t.c. What to run for building app.  I'll try to debug code.

**Comment by sigoden** [comment]
1. setup rust
https://www.alpharithms.com/installing-rust-on-windows-403718/
2. run windows-switcher
```
git clone https://github.com/sigoden/window-switcher
cd window-switcher
cargo run
```

**Comment by Shuraken007** [comment]
Well it was a nice journey. I debugged and founded some things.

1. I used right_alt with code 165, and you accept left_alt.
Just have ergo-keyboard, and alt+tab looks other way.

![IMG_20230514_232538](https://github.com/sigoden/window-switcher/assets/23379636/d39cbee0-84bb-41e4-b971-53258ebd3901)

2. Case I minimize any app, use start+d as example - I can't switch to anything, you filtered all apps and blocked them from windows list. Iconic option turns from true to false and you blocked it.

I added this code to debug required processes and got all your options
```
    let is_visible = is_visible_window(hwnd);
    let is_special = is_special_window(hwnd);
    let is_small = is_small_window(hwnd);
    let is_cloaked = is_cloaked_window(hwnd);
    let is_popup = is_popup_window(hwnd);
    let is_iconic = is_iconic_window(hwnd);
    let is_topmost = is_topmost_window(hwnd);
    let pid = get_window_pid(hwnd);
    let module_path = get_module_path(pid);

        debug!("visible: {:?}, special: {:?}, small: {:?}, cloaked: {:?}, popup: {:?}, iconic: {:?}, topmost: {:?}, pid: {:?}, hwnd: {:?}, p: {:?}", 
            if is_visible_window(hwnd) {'+'} else {'-'},
            if is_special {'+'} else {'-'},
            if is_small {'+'} else {'-'},
            if is_cloaked {'+'} else {'-'},
            if is_popup {'+'} else {'-'},
            if is_iconic {'+'} else {'-'},
            if is_topmost {'+'} else {'-'},
            pid,
            hwnd,
            Path::new(& module_path).file_name().unwrap().to_str().unwrap(),
        ); 
```

Here is side by side difference at state, when it's possible to switch and when not.
[report_iconic.log](https://github.com/sigoden/window-switcher/files/11473114/report_iconic.log)

3. I have music application, and it uses ApplicationFrameHost.exe.

> This process is related to Universal Windows Platform Applications (also known as Store Applications - a new type of application that comes with Windows 10). Although most of the apps that come with Windows 10 (such as Mail, Calculator, OneNote, Movies & TV, Photos and Groove Music) are UWP apps, these are available from the Windows Store. If this process is forcibly ended, all open UWP apps will be closed.

So, all apps, based on this FrameHost - are same for you. As example basic app calculator and mine app for music. You can try it with 2 apps - calculator and 'Movies & TV'

App looks like this
![Screenshot_2](https://github.com/sigoden/window-switcher/assets/23379636/ba11b39b-8878-48d2-9391-3253e0bd76ac)
and got default exe icon
![ApplicationFrameHost_Icon](https://github.com/sigoden/window-switcher/assets/23379636/0ac67ad5-8702-4589-8526-79c460f6e45d)

I made same debug output for ApplicationFrameHost, containing music app, and processes, containing app name. 
[report_music.log](https://github.com/sigoden/window-switcher/files/11473144/report_music.log)

Looks, like child processes must be checked.

**Comment by sigoden** [comment]
Thanks for your contribution.

I apologize for replying so late. 

#47 solved point 1.
#48 solved point 3.

The point 2 is tricky. I can't find a way to restore the minimized uwp window.

**Comment by Shuraken007** [comment]
Good update.  Tw, what is sense of iconic condition? I removed it from that filter, and all works.

**Comment by sigoden** [comment]
Iconic is no longer needed.

**Comment by sigoden** [comment]
#50 solved restore the minimized uwp window.

All done.
