### ISSUE TITLE
Previews+ Better Window Selection

### ISSUE THREAD

**Issue by guydht** [sigoden/window-switcher#55]
Hi

First, just wanna say I love this. The only app which lets me switch between applications instead of just apps.

I come from Ubuntu, and there they have a very similar functionality to window-switcher, but they have 2 more features which I think are really nice to have

1. Previewing of windows when alt-tab-ing
2. Switching windows inside application, while alt-tabbing

Here's a picture showing what I mean (found randomly online)
https://didrocks.fr/images/artful-shell-transition/alt-tab-application-multiple-windows.png

An example might help explain this feature better.
Let's say you have 2 chrome windows and an explorer window. You alt-tab to cycle to the chrome window, then while on the chrome icon you press ` (backtick) to cycle between chrome's windows.

Oh and another minor thing, the icons look fairly blury when alt+tab-ing, maybe it's because I have a high resolution screen, but it really does look pixelated  (here's an example on how it looks:)
![image](https://github.com/sigoden/window-switcher/assets/19510104/51c31462-86e6-4b32-b019-b8b12ccd50a4)

**Comment by guydht** [comment]
Oh and another nice-to-have is to be able to navigate the alt-tab menu using the arrow keys (again, like ubuntu)

**Comment by sigoden** [comment]
- #56 allows switching windows of the current selected application while alt-tab-ing. 
- The only reason the icon looks pixelated is that the application exe only provides small icon.
- Hold down the shift key to switch the reverse. and Mouse clicks work too.

**Comment by guydht** [comment]
You can just say it's too big of a feature.....

And about the pixalation, I doubt discord, whatsapp and chrome all provide only small icons....
And I get that you can shift-tab to reverse, I just said arrow keys would be nice.

**Comment by sigoden** [comment]
I was also surprised by the icons, the ones included in the exe are indeed incredibly small. 
For example, chrome is 44x44, discord is 32x32.

window-switcher requires 64x64, so they looks pixalation.
