### ISSUE TITLE
Feature want: custom list for the windows switcher

### ISSUE THREAD

**Issue by a-little-cat** [sigoden/window-switcher#58]
Can we input some keywords in the config;
like chrome, vscode, terminal;

then alt+` just switch between the windows which just related to the keywords.

**Comment by sigoden** [comment]
Use a blacklist to filter apps that don't want to use alt+`

```ini
[switch-windows]
# List of hotkey conflict apps
# e.g. game1.exe,game.exe
blacklist =
```

**Comment by a-little-cat** [comment]
nice!
