### ISSUE TITLE
Switching back to minimized apps chooses n+1.

### ISSUE THREAD

**Issue by pushqrdx** [sigoden/window-switcher#60]
#### Current Behavior:
If you have a minimized application with multiple windows open, when you try to switch to that application, instead of unminimizing last active window, you get the next one. For example, if you have 3 windows open and your last minimized one was window number 2, window-switcher will unminimize window number 3. If window number 3 was the last active one you get back window number 1 etc.

#### Expected Behavior:
Last active minimized window should be the one restored. 

---

I have quickly skimmed the code and I believe the issue lies in the logic [here](https://github.com/sigoden/window-switcher/blob/cd09f726026ef0e77c59f7ecf0c8d030a47ba2b8/src/app.rs#L352)?

Anyway, very useful application, thanks for working on it!

**Comment by sigoden** [comment]
Suppose there are three notepad windows a.txt, b.txt, c.txt。 If you minimize a.txt, b.txt, c.txt in order，the topmost window will be a.txt other than c.txt. This is really weird.

Thank you for submitting this issue.
