### ISSUE TITLE
poor quality of icons

### ISSUE THREAD

**Issue by joelcho** [sigoden/window-switcher#65]
Env:

OS: Windows 10 22H2 19045.3031
Screen: 1920 x 1080

category: switch-app

window-switcher: all versions

![sct1](https://github.com/sigoden/window-switcher/assets/34619326/5d60df3a-f641-48d5-a0ce-d2658cf62fd1)

**Comment by sigoden** [comment]
For non-uwp apps, the window switcher can only get the icon from the exe file.

For many applications, the exe provides very small icons. For example, chrome is 44x44 and discord is 32x32.
window-switcher requires 64x64, so they look pixelated.

There is no good way to solve this problem.
