### ISSUE TITLE
A popup for Alt+` that shows thumbnails and window names

### ISSUE THREAD

**Issue by pushqrdx** [sigoden/window-switcher#67]
It would be really nice if the alt+` switcher shows window thumbnails like the regular Windows alt+tab, would make switching between windows a lot easier and avoid accidental unminimizing of windows.

**Comment by sigoden** [comment]
No. Compared to thumbnails/names, directly switching is more quickly and obviously.

**Comment by pushqrdx** [comment]
@sigoden well what about accidental unminimizing of windows using the current approach, I can't even begin to count the number of times I have a few windows minimized and using alt+` unminimizes them and messes with the ordering

**Comment by sigoden** [comment]
use `ignore_minimal = yes`
