### ISSUE TITLE
Non US keyboards (Europe)

### ISSUE THREAD

**Issue by uberkael** [sigoden/window-switcher#69]
Hi,
Great program!
I was thinking of sending a merge request but seems unnecessary.

Instead of **alt+\`** my custom keyboard use `alt+\` so there is no way to define it in the config.
Also in the case of some European layouts (like Spanish), the key is `º`.
Luckily in both cases, the keycode behind is the same `VK_OEM_5` and corresponds with `0xDC` according to https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

[`0xDC` is already mapped as `|` in the code](https://github.com/sigoden/window-switcher/blob/bea734bfe6471eaf76e4419b0e1daf0cb31b60e3/src/config.rs#L247C16-L247C16) and I can confirm that defining  `alt+|` works.
Maybe it can be documented or add some other symbols to the mapping (like `º` and `\\`).

Thanks.

**Comment by sigoden** [comment]
Two steps to set hotkey for non use keyboards:

1. check keyboard layout at http://kbdlayout.info/00000409/shortcut/29 to see the hotkey is OEM-?
2.  use mapping code of OME-?
```
            ":" | ";" => 0xba,  // VK_OEM_1
            "+" | "=" => 0xbb,  // VK_OEM_PLUS
            "<" | "," => 0xbc,  // VK_OEM_COMMA
            "-" | "_" => 0xbd,  // VK_OEM_MINUS
            ">" | "." => 0xbe,  // VK_OEM_PERIOD
            "?" | "/" => 0xbf,  // VK_OEM_2
            "~" | "`" => 0xc0,  // VK_OEM_3
            "{" | "[" => 0xdb,  // VK_OEM_4
            "|" | "\\" => 0xdc, // VK_OEM_5
            "}" | "]" => 0xdd,  // VK_OEM_6
            "\"" | "'" => 0xde, // VK_OEM_7
            "§" | "!" => 0xdf,  // VK_OEM_8
```

**Comment by theotherp** [comment]
So 
```
[switch-windows]
hotkey = alt+0xc0
```

for OEM-3? That doesn't work for me. I think it should be explained (better) in the Readme.
