### ISSUE TITLE
App icon is not listed while the app opens a dialog.

### ISSUE THREAD

**Issue by oganii** [sigoden/window-switcher#73]
Hi.

When I upload my local file with Edge( Edge opens file selection dialog),
I can switch another app with alt+tab( a filer to copy file path to upload ),
but cannot switch back to Edge with alt+tab because Edge icon not displayed on the swithing list.

Thanks.

**Comment by joelcho** [comment]
I reproduced your problem on v1.2.1 which is fixed in the latest code.

Please pull the main branch, compile, and use it

**Comment by oganii** [comment]
I tried latest code, and confirmed the issue has been cleared.
Thank you for your effort.
