### ISSUE TITLE
Feature request: support custom icon of application

### ISSUE THREAD

**Issue by thaonguyen-ct** [sigoden/window-switcher#75]
Hi there,
I've just moved from MacOS to Windows and I really love this application, it's familiar with cmd + tab in MacOS. But it doesn't show the correct icon of some applications like ChatGPT, it shows the icon of Microsoft Edge instead of the icon of ChatGPT. And when I run Ubuntu via Windows Terminal, I want to custom the icon that will show icon of Windows Terminal instead of Ubuntu icon.
So it would be nice if I can custom the icon of application via the window-switcher.ini file, something like:
chatgpt.exe = D:\icon\chatgpc.ico
ubuntu.exe = D:\icon\ubuntu.ico
![image](https://github.com/sigoden/window-switcher/assets/46550685/f7e48f33-2f3e-4edf-bc7b-860c1025a1f2)
Thank you!

**Comment by sigoden** [comment]
As #76 fixed the problem, there is no need to set the icon manually.
