### ISSUE TITLE
Alt + Tab Key Behavior

### ISSUE THREAD

**Issue by lukedumboy** [sigoden/window-switcher#79]
When I press Alt+Tab in Chrome to switch between applications, if I want to hold down Alt and then press the left or right arrow keys to switch to different applications, Chrome recognizes it as going back or forward in the browsing history. This doesn't align with the expected behavior. Shouldn't I be able to switch applications with the left and right keys while keeping Alt held down?

**Comment by sigoden** [comment]
window switcher don't support `alt+left`/`alt+right` hotkeys.

**Comment by shinebayar-g** [comment]
You should be able to rotate backwards by clicking Alt + Shift + Tab
