### ISSUE TITLE
Esc key to close switcher

### ISSUE THREAD

**Issue by stianhoiland** [sigoden/window-switcher#80]
Thank you, thank you, thank you for making this!

Something I often do with both the macOS switcher (which this switcher imitates) and the Windows switcher and is really muscle-memoried into me is to close the switcher with the Escape key. I might open the switcher, look around, change my mind, and then close the switcher with Escape (obviously while Alt is still held down and with no switching to the highlighted app).

I would love for window-switcher to have this simple functionality: Close the switcher on Escape key.

At the moment any Alt-based hotkeys not explicitly handled by window-switcher's keyboard handler falls through to the active window (like Alt-F4!), and Alt+Esc is a global Windows hotkey ("Cycle through items in the order in which they were opened."), which really messes up my muscle memory when using window-switcher. I think window-switcher should consume as many keystrokes as is possible while the switcher window is visible (see #81).

**Comment by sigoden** [comment]
No, releasing a hotkey to close switcher is more natural than `esc`

**Comment by stianhoiland** [comment]
> No, releasing a hotkey to close switcher is more natural than `esc`

This means there is no easy way to "undo" the invocation of the switcher. Both Windows and macOS does this (using Esc to close the switcher).

**Comment by sigoden** [comment]
switching windows of the same app is realtime. no way to undo.

Switching apps can be undo using `shift`, such as `alt + shift + tab`

**Comment by mcuiux** [comment]
I'd like to add a +1 for this feature request.

Canceling out of an action is an important part of any UX, I'd really appreciate this as an option in the config.

There's an autohotkey version of this (https://github.com/Osmagtor/AppSwitcher/ - I modified it and posted my changes in the "issues") but I'd prefer to use this Rust version, if it could exit when I press Esc - as that's what I use when I work on my Mac at home :)

Thanks for making this!
