### ISSUE TITLE
Consume unhandled keystrokes to avoid accidental hotkeys

### ISSUE THREAD

**Issue by stianhoiland** [sigoden/window-switcher#81]
At the moment any Alt-based hotkeys not explicitly handled by window-switcher's keyboard handler falls through to the active window (like Alt-F4!). I think window-switcher should consume as many keystrokes as is possible while the switcher window is visible to avoid accidentally invoking Alt-based hotkeys when the task or visual context is obviously the switcher.

Thanks again for making this!

**Comment by sigoden** [comment]
No, windows-switcher only has two functions: ```alt+` ``` switch windows of tge same app, `alt + tab` switch app

No more, no less, simple and clear
