### ISSUE TITLE
Do not wrap around app icons row on key repeat

### ISSUE THREAD

**Issue by stianhoiland** [sigoden/window-switcher#82]
One feature of the macOS switcher that I use often is that while cmd+tab (which is macOS's alt+tab) is being held down, the switcher rapidly succeeds through the app icons (because of underlying key repeat), and window-switcher also does this. But when the macOS switcher gets to the end (rightmost) of the app icons, it stops. It doesn't automatically wrap around on key repeat. To wrap around to the start (leftmost) app icon, you have to let go of tab and press tab once to actually warp around. The very same key press that wraps around can be held down to start key repeating and rapidly succeeding again.

This is very useful to get to the last, second-last or third-last app quickly (by key repeating to the end and then reversing from the end of the icon row) without missing it and wrapping around and having to use shift to reverse.

This is a feature I would love to see!

**Comment by sigoden** [comment]
The current switching is closer to the habits of Windows users. The built-in`alt+tab`  is wrap mode.
