### ISSUE TITLE
German Keyboard / MacOS + Ubuntu behavior

### ISSUE THREAD

**Issue by btxtiger** [sigoden/window-switcher#86]
Hi there, I am so grateful for this tool. This was always a missing key feature in Windows!

I would like to achieve the same behavior like in MacOS with German Keyboard layout. But I wasn't able to find the correct configuration.

What I tried:
```ini
[switch-windows]
hotkey = Alt+^
hotkey = Alt+Dead
hotkey = Alt+Dead_Grave
hotkey = Alt+Dead_Circumflex
hotkey = Alt+VK_OEM_5
```

![image](https://github.com/sigoden/window-switcher/assets/15804690/808c1bc2-aa65-43d0-92c8-6d1ae0ac98d5)

**Comment by sigoden** [comment]
Steps to find non-English keyboard hotkeys:
1. go to http://kbdlayout.info/shortcut, select Keyboard layout  and keys
![image](https://github.com/sigoden/window-switcher/assets/4012553/33d359b6-414e-43e6-b773-ff1145cb28a4)

2. map to keycode
According to [keycodes](https://github.com/sigoden/window-switcher/blob/f43a89e5dc0a9306d1eceb9a69fa9169c456fa49/src/config.rs#L248), the hotkey for your german keyboard is `alt+|`.

After #87, you can use `ALT+VK_OEM_5` .

**Comment by btxtiger** [comment]
`alt+|` worked!! Thanks 🚀
