### ISSUE TITLE
loosing focus after switching apps or a window

### ISSUE THREAD

**Issue by Md97SalahUddin** [sigoden/window-switcher#88]
the issue persists in both app switching and window switching.lets say im watching a video in youtube if i switch to vlc space button doesnt work to play or pause the video.insted it focuses to global menu like pressing alt button alone activates the globul menu.I think it is emulating the macos behaviour like after switching window i have press right click inside the window.Hoawever the issue doesnt happen during lets say typing on vscode or searh bar of the browser,i only notice the loosing focus only during watching videos.I dont think windows alt+tab have this issue all the time, sometimes i notice it.

**Comment by sigoden** [comment]
Can't confirm the problem.


https://github.com/sigoden/window-switcher/assets/4012553/808a72aa-496f-47f5-982d-5706af4a165e

You can see from the video that after switching from vscode back to vlc via `alt+tab`, you can still pause vlc video playback via the `space` key.

**Comment by phcamargo23** [comment]
This problem also bothers me. From what you can see, it only happens that we change the window quickly. If you toggle smoothly, the focus remains, but if you do it quickly, it appears to trigger an automatic "alt" press, causing the focus to go to the toolbar

https://github.com/sigoden/window-switcher/assets/5577637/86cb6fca-2630-4f67-8ab2-e0c032e2fd4e
