### ISSUE TITLE
[SOLVED]Support of App Switcher for System Apps/Task Scheduler to Start with Admin Privileges

### ISSUE THREAD

**Issue by tsg-03** [sigoden/window-switcher#94]
Whenever I open Win32 system apps like Task Manager and Device Manager, it defaults to the stock Windows 11 App Switcher. I don't know how could you implement this but hopefully in the future, users can also use your app switcher with Win32 system apps.

I do not know if this is related, but I've used an app back then that supports apps with admin privileges. [see this](https://raw.githubusercontent.com/ClementGre/ThreeFingerDragOnWindows/main/ThreeFingerDragOnWindows/Assets/Screenshot-3.png)

Still, I like your app as windows easily clutter in the default Windows app switcher. Kudos!

**Comment by sigoden** [comment]
To enable `window-switcher` to switch system applications, you need to first grant `window-switcher system` permissions.

Please run `window-switcher.exe` as Administrator.

![image](https://github.com/sigoden/window-switcher/assets/4012553/2dd38dce-61f7-4ee6-985e-2bcbc9fc074c)

**Comment by tsg-03** [comment]
It seems to work. However, can you navigate me how to start this program at Startup with admin privileges enabled? I cannot seem to work my way with Task Scheduler. I'd appreciate any assistance. Thanks!

**Comment by sigoden** [comment]
### Task Scheduler

1. **Open Task Scheduler**: You can do this by searching for "Task Scheduler" in the Start menu.
2. **Create a New Task**: In the Task Scheduler, navigate to "Action" > "Create Task..."
3. **General Tab Settings**:
    - Give your task a name.
    - Check "Run with highest privileges".
    - Configure for your Windows version if necessary.
4. **Triggers Tab**: Click "New..." and choose "At startup" for "Begin the task".
5. **Actions Tab**:
    - Click "New...".
    - For "Action", choose "Start a program".
    - Browse and select the program you want to start or input the path manually.
6. **Conditions and Settings Tabs**: Adjust these settings as necessary for your needs.
7. **OK/Save**: Once you've configured your task, click "OK" to save it. You might be prompted to enter an admin password.

**Comment by tsg-03** [comment]
It didn't work initially following specific steps as per your advise. 

Though, after some research, I saw a Microsoft forum regarding the error code within the Task Scheduler: Not running (0x41303).
[Forum: task scheduler the task has not yet run (0x41303)](https://learn.microsoft.com/en-us/answers/questions/157259/task-scheduler-the-task-has-not-yet-run-(0x41303))

_please try to set "Conditions > Network" as "Any connection" to see if it helps_

And now, it worked! Commenting this down for future reference.

**Comment by tsg-03** [comment]
Thanks! (I forgot to close with comment; I'm still new to this.)
