### ISSUE TITLE
Detect Malware?

### ISSUE THREAD

**Issue by gimphammer** [sigoden/window-switcher#96]
![image](https://github.com/sigoden/window-switcher/assets/29744260/f4aa4f5a-9405-48f0-9d9f-9238c5b56c82)

**Comment by sigoden** [comment]
There are too many anti-virus software on the market and there may be false positives
The project is written in Rust and stripped of binaries to minimize,  More likely to be falsely reported.

https://www.virustotal.com/gui/file/84aab44ee5ba5b2b4f7f9aedb741b2ebdc2db340fe5640a7c3cf1eceb6c8e7d6

I just checked on Windows security, it did not report a virus.
